### ISSUE TITLE
Observed panic on receipt of routing message

### ISSUE THREAD

**Issue by gertjaap** [mit-dci/lit#290]
```2018/07/25 06:06:00.293406 decrypted message is 707d1a2ef87b639d918e9a67d469de93403a99c153c76db4dbd45c19924502844945245ba5db58fe92000000000007a1200532dc3002dbbdbd61483837394bfc14bd3cc7560000010100000002
2018/07/25 06:06:00.293454 peerIdx is 1
2018/07/25 06:06:00.293459 routed bytes 707d1a2ef87b639d918e9a67d469de93403a99c153c76db4dbd45c19924502844945245ba5db58fe92000000000007a1200532dc3002dbbdbd61483837394bfc14bd3cc7560000010100000002
2018/07/25 06:06:00.293461 message type 70
2018/07/25 06:06:00.293464 chanIdx is 0
2018/07/25 06:06:00.293466 Message from 1 type 70
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8be300]

goroutine 15 [running]:
github.com/mit-dci/lit/qln.(*LitNode).advertiseLinks(0xc4200ee1e0, 0x2)
	/usr/local/go/src/github.com/mit-dci/lit/qln/routing.go:97 +0x130
github.com/mit-dci/lit/qln.(*LitNode).InitRouting.func1(0xc4200ee1e0)
	/usr/local/go/src/github.com/mit-dci/lit/qln/routing.go:27 +0x47
created by github.com/mit-dci/lit/qln.(*LitNode).InitRouting
	/usr/local/go/src/github.com/mit-dci/lit/qln/routing.go:22 +0x106
```

**Comment by gertjaap** [comment]
Never mind, was related to something else (my own mistake)
