### ISSUE TITLE
Help command doesn't work

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#348]
`./lit -h` results in a grouting crash
```
goroutine 1 [running]:
main.litSetup(0xc4201ba000, 0x0)
	/Users/varunramg/go/src/github.com/mit-dci/lit/litinit.go:100 +0x9ac
main.main()
	/Users/varunramg/go/src/github.com/mit-dci/lit/lit.go:174 +0x172
```
It also prints the help output twice. Will put in a PR to fix this.

**Comment by Varunram** [comment]
Fixed in recent merges.
