### ISSUE TITLE
lndc_test.go fails

### ISSUE THREAD

**Issue by jnewbery** [mit-dci/lit#44]
running lndc_test.go fails:

```
→ go test .
# github.com/mit-dci/lit/lndc
lndc/lndc_test.go:43: cannot use localPriv.PubKey().SerializeCompressed() (type []byte) as type string in argument to conn.Dial
```

I've tried changing the []byte to a string in call to `conn.Dial()`:

```
@@ -40,7 +40,7 @@ func TestConnectionCorrectness(t *testing.T) {
        wg.Add(1)
        go func() {
                dialErr = conn.Dial(remotePriv, listener.Addr().String(),
-                       localPriv.PubKey().SerializeCompressed())
+                       string(localPriv.PubKey().SerializeCompressed()))
                wg.Done()
        }()
```

but lndc_test now times out after 10 minutes and fails:

```
→ go test -v .
=== RUN   TestConnectionCorrectness
SIGQUIT: quit
PC=0x45af01 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x95ded0, 0x0, 0x0, 0x0, 0x7f5000000000, 0xa42cd940, 0x0, 0x0, 0x7ffea42cd970, 0x40f32b, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:422 +0x21
runtime.futexsleep(0x95ded0, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x95ded0)
	/usr/local/go/src/runtime/lock_futex.go:145 +0x6b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc420022600, 0x0)
	/usr/local/go/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2222 +0x14c
runtime.park_m(0xc4204309c0)
	/usr/local/go/src/runtime/proc.go:2285 +0xab
runtime.mcall(0x7ffea42cdb00)
	/usr/local/go/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc42047e270, 0x6f1db0, 0x19, 0x81f880, 0xc42043fd20)
	/usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc42047e270)
	/usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc42047e270, 0xc42043fde0)
	/usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc420474220, 0x951900, 0x1, 0x1, 0xc42043fed0)
	/usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc420497f20, 0xc42043ff20)
	/usr/local/go/src/testing/testing.go:822 +0xfc
main.main()
	github.com/mit-dci/lit/lndc/_test/_testmain.go:42 +0xf7

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [semacquire, 9 minutes]:
sync.runtime_notifyListWait(0xc420432a50, 0xc400000000)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420432a40)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/btcsuite/seelog.(*asyncLoopLogger).processItem(0xc420072e40, 0x0)
	/home/john/Code/go/src/github.com/btcsuite/seelog/behavior_asynclooplogger.go:50 +0x97
github.com/btcsuite/seelog.(*asyncLoopLogger).processQueue(0xc420072e40)
	/home/john/Code/go/src/github.com/btcsuite/seelog/behavior_asynclooplogger.go:63 +0x33
created by github.com/btcsuite/seelog.newAsyncLoopLogger
	/home/john/Code/go/src/github.com/btcsuite/seelog/behavior_asynclooplogger.go:40 +0x96

goroutine 6 [semacquire, 9 minutes]:
sync.runtime_notifyListWait(0xc420432bd0, 0xc400000000)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420432bc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/btcsuite/seelog.(*asyncLoopLogger).processItem(0xc420072f60, 0x0)
	/home/john/Code/go/src/github.com/btcsuite/seelog/behavior_asynclooplogger.go:50 +0x97
github.com/btcsuite/seelog.(*asyncLoopLogger).processQueue(0xc420072f60)
	/home/john/Code/go/src/github.com/btcsuite/seelog/behavior_asynclooplogger.go:63 +0x33
created by github.com/btcsuite/seelog.newAsyncLoopLogger
	/home/john/Code/go/src/github.com/btcsuite/seelog/behavior_asynclooplogger.go:40 +0x96

goroutine 10 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f50bd225a78, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200aa068, 0x72, 0x93a080, 0x937440)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200aa068, 0xc4200120d8, 0x2)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4200aa000, 0xc4200120d8, 0x2, 0x8, 0x0, 0x93a080, 0x937440)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4200a0000, 0xc4200120d8, 0x2, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
io.ReadAtLeast(0x7f50bc1a0000, 0xc4200a0000, 0xc4200120d8, 0x2, 0x8, 0x2, 0x6901c0, 0x7f50bc1a0001, 0xc4200120d8)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x7f50bc1a0000, 0xc4200a0000, 0xc4200120d8, 0x2, 0x8, 0x50, 0x16, 0x1)
	/usr/local/go/src/io/io.go:325 +0x58
encoding/binary.Read(0x7f50bc1a0000, 0xc4200a0000, 0x93e680, 0x978f60, 0x67fa60, 0xc4200120d0, 0x81fa38, 0x27)
	/usr/local/go/src/encoding/binary/binary.go:170 +0xea
github.com/mit-dci/lit/lndc.readClear(0x93e8c0, 0xc4200a0000, 0x454020, 0x7f50bfa4ce10, 0xe, 0xc420041c90, 0x4106e2)
	/home/john/Code/go/src/github.com/mit-dci/lit/lndc/netio.go:60 +0xdc
github.com/mit-dci/lit/lndc.(*Listener).createCipherConn(0xc420452240, 0xc420076000, 0xc4200a0000, 0x0, 0x0, 0xc420041d08, 0x657548)
	/home/john/Code/go/src/github.com/mit-dci/lit/lndc/listener.go:75 +0x53
github.com/mit-dci/lit/lndc.(*Listener).Accept(0xc420452240, 0x81f878, 0xc420452260, 0xc42047e410, 0xc4204762a0)
	/home/john/Code/go/src/github.com/mit-dci/lit/lndc/listener.go:53 +0xb4
github.com/mit-dci/lit/lndc.TestConnectionCorrectness(0xc42047e340)
	/home/john/Code/go/src/github.com/mit-dci/lit/lndc/lndc_test.go:47 +0x369
testing.tRunner(0xc42047e340, 0x81f880)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca

rax    0xca
rbx    0x0
rcx    0x45af03
rdx    0x0
rdi    0x95ded0
rsi    0x0
rbp    0x7ffea42cd940
rsp    0x7ffea42cd8f8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xc4200689c0
r14    0x440340
r15    0x8792e0
rip    0x45af01
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/mit-dci/lit/lndc	600.004s
```

**Comment by jnewbery** [comment]
fixed by a75fcdddf44f64e784f03f3c8ec3b029cf179f32
